### ISSUE TITLE
runtime error: SSE4.1 instructions aren't available

### ISSUE THREAD

**Issue by Sinan81** [lbeaucourt/Object-detection#14]
First of all, thanks for creating this repository, which I enjoyed playing with.

I just want to point out that the default tensorflow python package is compiled for somewhat newer generations of CPUs and accordingly when I tried to ran Object-detection container in two of my ~7 year old computers, I am getting the following run-time error:
````
2018-11-29 09:24:03.044846: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use SSE4.1 instructions, but these aren't available on your machine.
exec.sh: line 1:     7 Aborted                 (core dumped) python3 my-object-detection.py -d 1 -o 1 -I -w 2 -q-size 5
````
since not so new CPUs don't have SSE4.1 instruction sets.

It turns out that beyond version 1.6, Tensorflow requires SSE4.1 compatibility. Hence one either needs to use tensorflow python package version 1.6 or earlier (which yields another runtime error) or tensorflow python package needs to be build from source.

Hope this issue report might be of help to some users.

**Comment by lbeaucourt** [comment]
H!

Thanks for your feedback. I will had your comment in the README!

**Comment by Sinan81** [comment]
Thanks! I attempted to improve the wording a bit and submitted PR#17. Hope thats ok.
