### ISSUE TITLE
what is "worker" in  pool = Pool(args["num_workers"], worker, (input_q,output_q)) ?

### ISSUE THREAD

**Issue by ThorPham** [lbeaucourt/Object-detection#18]

**Comment by lbeaucourt** [comment]
Hello,

worker are defined here: https://github.com/lbeaucourt/Object-detection/blob/master/utils/objDet_utils.py

Workers takes frames from input queue and apply object detection. You can send number of workers as parameters of the main function.

**Comment by ThorPham** [comment]
Thank you for your reply. I have other question. How to i get bounding box each detection when i run video realtime with multiprocessing ( queue output). I have camera ip and want to put value bounding box on web server .

**Comment by lbeaucourt** [comment]
You can found boxes in the detect_objects function (in the same file as worker). Inputs are un-processed frame, objet detection model is apply on frame and the function return updated frame with detection results. The boxes coordinates, classes and scores are produced with this code:

# Actual detection.
(boxes, scores, classes, num_detections) = sess.run(
[boxes, scores, classes, num_detections], feed_dict={image_tensor: image_np_expanded})


You can get the boxes by changing the return of this function and add boxes, classes or whatever you want. (Check also that boxes are returned at each stages).

**Comment by ThorPham** [comment]
Thank so much!
