### ISSUE TITLE
Video window not showing

### ISSUE THREAD

**Issue by DanishAbsar** [lbeaucourt/Object-detection#21]
The camera is active, a video store in output but video window unable to load

**Comment by lbeaucourt** [comment]
Hi Danish,

Be sure to set the display option to True (-d 1 in exec.sh). What's errors did you get?


Regards,

**Comment by DanishAbsar** [comment]
Hi @lbeaucourt Thanks for the prompt response, Actually I'm running Ubuntu 16.04 VM on my windows machine.

this is my exec.sh
`python3 my-object-detection.py -d 1 -o 1 -I 0 -w 20 -q-size 150`

when i run the runDocker i got following warning as well

```
non-network local connections being added to access control list
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
```
I use your runDocker.sh to run docker build of [this code ](https://github.com/datitran/object_detector_app) this work fine and Launch the video streaming windows. but no streaming video with following error:

```
[INFO] elapsed time: 0.05
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x320000b
[INFO] elapsed time: 0.05
```


When your build code is switch over mac:

no such above type warning but getting the following error

```
docker: Error response from daemon: error gathering device information while adding custom device "/dev/video0": no such file or directory.
non-network local connections being removed from access control list
```

Good Day

**Comment by lbeaucourt** [comment]
Hi @DanishAbsar , thanks for all these information.

I'm never tried to use this repo with linux VM on Windows. It was something I planned to try, but never found enough time. I found something here (https://github.com/P0cL4bs/WiFi-Pumpkin/issues/53), but it's not dedicated to VM and windows. Maybe you could try to set the env variable in your VM linux...

The first two lines of warning you get are normal, I get same.

The last error you get means that the docker can't find dev/video0 device, which is your webcam path in linux file system. Two reasons: 1) webcam is not available, 2) IOS file system doesn't name webcam device as Linux, you should find the name of your device and modify the runDocker.sh file (replace the --device=dev/video0 by --device=<IOS webcam path>


Hope it helps, furthermore I interested to know if you solve your problem and successfully run the repo on Windows/IOS.

regards

**Comment by DanishAbsar** [comment]
Thanks @lbeaucourt

I concluded it's not possible on mac using docker [reference](https://apple.stackexchange.com/questions/265281)

btw no dought it's a nice repo and works like a charm

**Comment by lbeaucourt** [comment]
HI @DanishAbsar ,

Thanks for your research. I will add this ref in the README with an advert about the supported OS for this repo.

regards
