### ISSUE TITLE
Without Docker

### ISSUE THREAD

**Issue by tomhayat** [lbeaucourt/Object-detection#3]
Hi,
Can I use it without a docker I have tried but got ```No module named 'object_detection' ```?
Thank you very much

**Comment by lbeaucourt** [comment]
Hi Tom.

Sure you can. You need to correctly install the object_detection API from tensorflow. Run the same command as in my dockerfile (without the RUN):

# Install tensorFlow and keras
pip install -U tensorflow
pip install -U keras

# Install tensorflow models object detection
git clone https://github.com/tensorflow/models /usr/local/lib/python3.5/dist-packages/tensorflow/models
apt-get install -y protobuf-compiler python-pil python-lxml python-tk

Then you should "say" to linux where is your local install of tensorflow object_detection:

#Set TF object detection available
export PYTHONPATH=$PYTHONPATH:/usr/local/lib/python3.5/dist-packages/tensorflow/models/research:/usr/local/lib/python3.5/dist-packages/tensorflow/models/research/slim
cd /usr/local/lib/python3.5/dist-packages/tensorflow/models/research 
protoc object_detection/protos/*.proto --python_out=.

Take a look at: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md

Hope that help you ;)

**Comment by lbeaucourt** [comment]
Hi Tom,

Can I close the issue?
