### ISSUE TITLE
Ssd is not defined

### ISSUE THREAD

**Issue by lily0101** [lbeaucourt/Object-detection#4]
HI,I use "sudo docker build -t realtime-objectdetection .
" to make the image, but I get the error below. I don't know what's wrong with that.
My real linux is ubuntu14.04.
please help me with that!

Step 31/32 : RUN cd /usr/local/lib/python3.5/dist-packages/tensorflow/models/research && protoc object_detection/protos/*.proto --python_out=.
 ---> Running in 311da9917ecb
object_detection/protos/ssd.proto:87:3: Expected "required", "optional", or "repeated".
object_detection/protos/ssd.proto:87:12: Expected field name.
object_detection/protos/model.proto: Import "object_detection/protos/ssd.proto" was not found or had errors.
object_detection/protos/model.proto:12:5: "Ssd" is not defined.
The command '/bin/sh -c cd /usr/local/lib/python3.5/dist-packages/tensorflow/models/research && protoc object_detection/protos/*.proto --python_out=.' returned a non-zero code: 1

**Comment by lily0101** [comment]
@lbeaucourt  Hi, 
 I still can't sovle that problem by cloning the project again. the error is below:
`Step 31/32 : RUN cd /usr/local/lib/python3.5/dist-packages/tensorflow/models/research && protoc object_detection/protos/*.proto --python_out=.
 ---> Running in 8b5f9bcacbac
object_detection/protos/ssd.proto:87:3: Expected "required", "optional", or "repeated".
object_detection/protos/ssd.proto:87:12: Expected field name.
object_detection/protos/model.proto: Import "object_detection/protos/ssd.proto" was not found or had errors.
object_detection/protos/model.proto:12:5: "Ssd" is not defined.
The command '/bin/sh -c cd /usr/local/lib/python3.5/dist-packages/tensorflow/models/research && protoc object_detection/protos/*.proto --python_out=.' returned a non-zero code: 1
`
by the way,I have some questions about docker, in my real ubuntu14.04, there is no the dir " /usr/local/lib/python3.5/dist-packages/tensorflow/models/research", but is it in the virtul envs ubuntu16.04?

**Comment by lbeaucourt** [comment]
Hi @lily0101 !

I have solved the problem (I hope). Tensorflow object-api has been updated and now requires a new version of proto-compiler. I changed the Dockerfile to get the correct version ! Let's try and see if it works now.

Yes it is normal that you cannot find directory "/usr/local/lib/python3.5/dist-packages/tensorflow/models/research" in your local ubuntu (unless you've installed tensorflow object-detection locally of course). 

The interesting point of docker is that you have not to install anything locally. A docker container (when you run a docker image) is a virtual env (in this case a ubuntu 16.04) in which you install all components you needs (e.g. what is listed in the Dockerfile). If you run your docker image with bash option at the end (in the runDocker.sh file), you will "enter" into the virtual ubuntu and you will be able to see the directory "/usr/local/lib/python3.5/dist-packages/tensorflow/models/research".

Hope this help you!

**Comment by lily0101** [comment]
@lbeaucourt  hi, thanks a lot, I solved that problem. 
But when I run the code `bash runDocker.sh` ,there are errors again, the errors are below:
`non-network local connections being added to access control list
xauth:  file /tmp/.docker.xauth does not exist
xauth: (argv):1:  unable to read any entries from file "(stdin)"
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
docker: Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device "/dev/video0": no such file or directory.
non-network local connections being removed from access control list
`
I searched in google, but did not work.

Do you know the reason? Please help me.

Thanks again!

**Comment by lbeaucourt** [comment]
Hi @lily0101,

Docker cannot find the dev/video0 file which corresponds to the integrated webcam device. Have you an integrated webcam or an USB webcam? Could you give me the result of this command line (in your local host): 

> ll /dev/video*

And if it returns nothing, try:

> ll /dev/

The "WARNING: Your kernel ..." is a normal output, I have the same.

**Comment by lily0101** [comment]
hi,@lbeaucourt 
when I run the first command,the result is below:
`
ls: 无法访问/dev/video*: 没有那个文件或目录
`
that means there is not the dir /dev/vedio*

when I run the second command,the result is below:

`
总用量 4
drwxr-xr-x  16 root root        4260  5月  2 09:02 ./
drwxr-xr-x  29 root root        4096  5月  4 08:29 ../
crw-------   1 root root     10, 235  5月  1 20:54 autofs
drwxr-xr-x   2 root root         660  5月  2 09:02 block/
drwxr-xr-x   2 root root          80  5月  2 09:02 bsg/
crw-------   1 root root     10, 234  5月  1 20:54 btrfs-control
drwxr-xr-x   3 root root          60  5月  1 20:54 bus/
drwxr-xr-x   2 root root        4120  5月  2 09:02 char/
crw-------   1 root root      5,   1  5月  1 20:54 console
lrwxrwxrwx   1 root root          11  5月  1 20:54 core -> /proc/kcore
drwxr-xr-x   2 root root          60  5月  1 20:54 cpu/
crw-------   1 root root     10,  60  5月  1 20:54 cpu_dma_latency
crw-------   1 root root     10, 203  5月  1 20:54 cuse
drwxr-xr-x   5 root root         100  5月  2 09:02 disk/
drwxr-xr-x   2 root root          80  5月  1 20:54 dri/
crw-------   1 root root     10,  61  5月  1 20:54 ecryptfs
crw-rw----   1 root video    29,   0  5月  1 20:54 fb0
lrwxrwxrwx   1 root root          13  5月  1 20:54 fd -> /proc/self/fd/
crw-rw-rw-   1 root root      1,   7  5月  1 20:54 full
crw-rw-rw-   1 root root     10, 229  5月  1 20:54 fuse
crw-------   1 root root    247,   0  5月  1 20:54 hidraw0
crw-------   1 root root    247,   1  5月  1 20:54 hidraw1
crw-------   1 root root     10, 228  5月  1 20:54 hpet
lrwxrwxrwx   1 root root          14  5月  1 20:54 .initramfs -> /run/initramfs/
drwxr-xr-x   4 root root         520  5月  1 20:54 input/
crw-r--r--   1 root root      1,  11  5月  1 20:54 kmsg
srw-rw-rw-   1 root root           0  5月  1 20:54 log=
brw-rw----   1 root disk      7,   0  5月  1 20:54 loop0
brw-rw----   1 root disk      7,   1  5月  1 20:54 loop1
brw-rw----   1 root disk      7,   2  5月  1 20:54 loop2
brw-rw----   1 root disk      7,   3  5月  1 20:54 loop3
brw-rw----   1 root disk      7,   4  5月  1 20:54 loop4
brw-rw----   1 root disk      7,   5  5月  1 20:54 loop5
brw-rw----   1 root disk      7,   6  5月  1 20:54 loop6
brw-rw----   1 root disk      7,   7  5月  1 20:54 loop7
crw-------   1 root root     10, 237  5月  1 20:54 loop-control
drwxr-xr-x   2 root root          60  5月  1 20:54 mapper/
crw-------   1 root root     10, 227  5月  1 20:54 mcelog
crw-------   1 root root     10,  57  5月  1 20:54 mei
crw-r-----   1 root kmem      1,   1  5月  1 20:54 mem
drwxr-xr-x   2 root root          60  5月  1 20:54 net/
crw-------   1 root root     10,  59  5月  1 20:54 network_latency
crw-------   1 root root     10,  58  5月  1 20:54 network_throughput
crw-rw-rw-   1 root root      1,   3  5月  1 20:54 null
crw-rw-rw-   1 root root    195,   0  5月  1 20:54 nvidia0
crw-rw-rw-   1 root root    195,   1  5月  1 20:54 nvidia1
crw-rw-rw-   1 root root    195, 255  5月  1 20:54 nvidiactl
crw-rw-rw-   1 root root    195, 254  5月  1 20:54 nvidia-modeset
crw-rw-rw-   1 root root    248,   0  5月  1 20:54 nvidia-uvm
crw-r-----   1 root kmem      1,   4  5月  1 20:54 port
crw-------   1 root root    108,   0  5月  1 20:54 ppp
crw-------   1 root root     10,   1  5月  1 20:54 psaux
crw-rw-rw-   1 root tty       5,   2  5月  4 20:16 ptmx
crw-------   1 root root    250,   0  5月  1 20:54 ptp0
drwxr-xr-x   2 root root           0  5月  1 20:54 pts/
brw-rw----   1 root disk      1,   0  5月  1 20:54 ram0
brw-rw----   1 root disk      1,   1  5月  1 20:54 ram1
brw-rw----   1 root disk      1,  10  5月  1 20:54 ram10
brw-rw----   1 root disk      1,  11  5月  1 20:54 ram11
brw-rw----   1 root disk      1,  12  5月  1 20:54 ram12
brw-rw----   1 root disk      1,  13  5月  1 20:54 ram13
brw-rw----   1 root disk      1,  14  5月  1 20:54 ram14
brw-rw----   1 root disk      1,  15  5月  1 20:54 ram15
brw-rw----   1 root disk      1,   2  5月  1 20:54 ram2
brw-rw----   1 root disk      1,   3  5月  1 20:54 ram3
brw-rw----   1 root disk      1,   4  5月  1 20:54 ram4
brw-rw----   1 root disk      1,   5  5月  1 20:54 ram5
brw-rw----   1 root disk      1,   6  5月  1 20:54 ram6
brw-rw----   1 root disk      1,   7  5月  1 20:54 ram7
brw-rw----   1 root disk      1,   8  5月  1 20:54 ram8
brw-rw----   1 root disk      1,   9  5月  1 20:54 ram9
crw-rw-rw-   1 root root      1,   8  5月  1 20:54 random
crw-rw-r--+  1 root root     10,  62  5月  1 20:54 rfkill
lrwxrwxrwx   1 root root           4  5月  1 20:54 rtc -> rtc0
crw-------   1 root root    254,   0  5月  1 20:54 rtc0
brw-rw----   1 root disk      8,   0  5月  1 20:54 sda
brw-rw----   1 root disk      8,   1  5月  1 20:54 sda1
brw-rw----   1 root disk      8,   2  5月  1 20:54 sda2
brw-rw----   1 root disk      8,   3  5月  1 20:54 sda3
brw-rw----   1 root disk      8,  16  5月  1 20:54 sdb
brw-rw----   1 root disk      8,  17  5月  1 20:54 sdb1
brw-rw----   1 root disk      8,  18  5月  1 20:54 sdb2
crw-rw----   1 root disk     21,   0  5月  1 20:54 sg0
crw-rw----   1 root disk     21,   1  5月  1 20:54 sg1
lrwxrwxrwx   1 root root           8  5月  1 20:54 shm -> /run/shm/
crw-------   1 root root     10, 231  5月  1 20:54 snapshot
drwxr-xr-x   3 root root         460  5月  1 20:54 snd/
lrwxrwxrwx   1 root root          15  5月  1 20:54 stderr -> /proc/self/fd/2
lrwxrwxrwx   1 root root          15  5月  1 20:54 stdin -> /proc/self/fd/0
lrwxrwxrwx   1 root root          15  5月  1 20:54 stdout -> /proc/self/fd/1
crw-rw-rw-   1 root tty       5,   0  5月  4 15:34 tty
crw--w----   1 root tty       4,   0  5月  1 20:54 tty0
crw-rw----   1 root tty       4,   1  5月  1 20:54 tty1
crw--w----   1 root tty       4,  10  5月  1 20:54 tty10
crw--w----   1 root tty       4,  11  5月  1 20:54 tty11
crw--w----   1 root tty       4,  12  5月  1 20:54 tty12
crw--w----   1 root tty       4,  13  5月  1 20:54 tty13
crw--w----   1 root tty       4,  14  5月  1 20:54 tty14
crw--w----   1 root tty       4,  15  5月  1 20:54 tty15
crw--w----   1 root tty       4,  16  5月  1 20:54 tty16
crw--w----   1 root tty       4,  17  5月  1 20:54 tty17
crw--w----   1 root tty       4,  18  5月  1 20:54 tty18
crw--w----   1 root tty       4,  19  5月  1 20:54 tty19
crw-rw----   1 root tty       4,   2  5月  1 20:54 tty2
crw--w----   1 root tty       4,  20  5月  1 20:54 tty20
crw--w----   1 root tty       4,  21  5月  1 20:54 tty21
crw--w----   1 root tty       4,  22  5月  1 20:54 tty22
crw--w----   1 root tty       4,  23  5月  1 20:54 tty23
crw--w----   1 root tty       4,  24  5月  1 20:54 tty24
crw--w----   1 root tty       4,  25  5月  1 20:54 tty25
crw--w----   1 root tty       4,  26  5月  1 20:54 tty26
crw--w----   1 root tty       4,  27  5月  1 20:54 tty27
crw--w----   1 root tty       4,  28  5月  1 20:54 tty28
crw--w----   1 root tty       4,  29  5月  1 20:54 tty29
crw-rw----   1 root tty       4,   3  5月  1 20:54 tty3
crw--w----   1 root tty       4,  30  5月  1 20:54 tty30
crw--w----   1 root tty       4,  31  5月  1 20:54 tty31
crw--w----   1 root tty       4,  32  5月  1 20:54 tty32
crw--w----   1 root tty       4,  33  5月  1 20:54 tty33
crw--w----   1 root tty       4,  34  5月  1 20:54 tty34
crw--w----   1 root tty       4,  35  5月  1 20:54 tty35
crw--w----   1 root tty       4,  36  5月  1 20:54 tty36
crw--w----   1 root tty       4,  37  5月  1 20:54 tty37
crw--w----   1 root tty       4,  38  5月  1 20:54 tty38
crw--w----   1 root tty       4,  39  5月  1 20:54 tty39
crw-rw----   1 root tty       4,   4  5月  1 20:54 tty4
crw--w----   1 root tty       4,  40  5月  1 20:54 tty40
crw--w----   1 root tty       4,  41  5月  1 20:54 tty41
crw--w----   1 root tty       4,  42  5月  1 20:54 tty42
crw--w----   1 root tty       4,  43  5月  1 20:54 tty43
crw--w----   1 root tty       4,  44  5月  1 20:54 tty44
crw--w----   1 root tty       4,  45  5月  1 20:54 tty45
crw--w----   1 root tty       4,  46  5月  1 20:54 tty46
crw--w----   1 root tty       4,  47  5月  1 20:54 tty47
crw--w----   1 root tty       4,  48  5月  1 20:54 tty48
crw--w----   1 root tty       4,  49  5月  1 20:54 tty49
crw-rw----   1 root tty       4,   5  5月  1 20:54 tty5
crw--w----   1 root tty       4,  50  5月  1 20:54 tty50
crw--w----   1 root tty       4,  51  5月  1 20:54 tty51
crw--w----   1 root tty       4,  52  5月  1 20:54 tty52
crw--w----   1 root tty       4,  53  5月  1 20:54 tty53
crw--w----   1 root tty       4,  54  5月  1 20:54 tty54
crw--w----   1 root tty       4,  55  5月  1 20:54 tty55
crw--w----   1 root tty       4,  56  5月  1 20:54 tty56
crw--w----   1 root tty       4,  57  5月  1 20:54 tty57
crw--w----   1 root tty       4,  58  5月  1 20:54 tty58
crw--w----   1 root tty       4,  59  5月  1 20:54 tty59
crw-rw----   1 root tty       4,   6  5月  1 20:54 tty6
crw--w----   1 root tty       4,  60  5月  1 20:54 tty60
crw--w----   1 root tty       4,  61  5月  1 20:54 tty61
crw--w----   1 root tty       4,  62  5月  1 20:54 tty62
crw--w----   1 root tty       4,  63  5月  1 20:54 tty63
crw--w----   1 root tty       4,   7  5月  1 20:54 tty7
crw--w----   1 root tty       4,   8  5月  1 20:54 tty8
crw--w----   1 root tty       4,   9  5月  1 20:54 tty9
crw-------   1 root root      5,   3  5月  1 20:54 ttyprintk
crw-rw----   1 root dialout   4,  64  5月  1 20:54 ttyS0
crw-rw----   1 root dialout   4,  65  5月  1 20:54 ttyS1
crw-rw----   1 root dialout   4,  74  5月  1 20:54 ttyS10
crw-rw----   1 root dialout   4,  75  5月  1 20:54 ttyS11
crw-rw----   1 root dialout   4,  76  5月  1 20:54 ttyS12
crw-rw----   1 root dialout   4,  77  5月  1 20:54 ttyS13
crw-rw----   1 root dialout   4,  78  5月  1 20:54 ttyS14
crw-rw----   1 root dialout   4,  79  5月  1 20:54 ttyS15
crw-rw----   1 root dialout   4,  80  5月  1 20:54 ttyS16
crw-rw----   1 root dialout   4,  81  5月  1 20:54 ttyS17
crw-rw----   1 root dialout   4,  82  5月  1 20:54 ttyS18
crw-rw----   1 root dialout   4,  83  5月  1 20:54 ttyS19
crw-rw----   1 root dialout   4,  66  5月  1 20:54 ttyS2
crw-rw----   1 root dialout   4,  84  5月  1 20:54 ttyS20
crw-rw----   1 root dialout   4,  85  5月  1 20:54 ttyS21
crw-rw----   1 root dialout   4,  86  5月  1 20:54 ttyS22
crw-rw----   1 root dialout   4,  87  5月  1 20:54 ttyS23
crw-rw----   1 root dialout   4,  88  5月  1 20:54 ttyS24
crw-rw----   1 root dialout   4,  89  5月  1 20:54 ttyS25
crw-rw----   1 root dialout   4,  90  5月  1 20:54 ttyS26
crw-rw----   1 root dialout   4,  91  5月  1 20:54 ttyS27
crw-rw----   1 root dialout   4,  92  5月  1 20:54 ttyS28
crw-rw----   1 root dialout   4,  93  5月  1 20:54 ttyS29
crw-rw----   1 root dialout   4,  67  5月  1 20:54 ttyS3
crw-rw----   1 root dialout   4,  94  5月  1 20:54 ttyS30
crw-rw----   1 root dialout   4,  95  5月  1 20:54 ttyS31
crw-rw----   1 root dialout   4,  68  5月  1 20:54 ttyS4
crw-rw----   1 root dialout   4,  69  5月  1 20:54 ttyS5
crw-rw----   1 root dialout   4,  70  5月  1 20:54 ttyS6
crw-rw----   1 root dialout   4,  71  5月  1 20:54 ttyS7
crw-rw----   1 root dialout   4,  72  5月  1 20:54 ttyS8
crw-rw----   1 root dialout   4,  73  5月  1 20:54 ttyS9
drwxr-xr-x   3 root root          60  5月  1 20:54 .udev/
crw-------   1 root root     10, 239  5月  1 20:54 uhid
crw-------   1 root root     10, 223  5月  1 20:54 uinput
crw-rw-rw-   1 root root      1,   9  5月  1 20:54 urandom
crw-rw----   1 root tty       7,   0  5月  1 20:54 vcs
crw-rw----   1 root tty       7,   1  5月  1 20:54 vcs1
crw-rw----   1 root tty       7,   2  5月  1 20:54 vcs2
crw-rw----   1 root tty       7,   3  5月  1 20:54 vcs3
crw-rw----   1 root tty       7,   4  5月  1 20:54 vcs4
crw-rw----   1 root tty       7,   5  5月  1 20:54 vcs5
crw-rw----   1 root tty       7,   6  5月  1 20:54 vcs6
crw-rw----   1 root tty       7,   8  5月  1 22:13 vcs8
crw-rw----   1 root tty       7, 128  5月  1 20:54 vcsa
crw-rw----   1 root tty       7, 129  5月  1 20:54 vcsa1
crw-rw----   1 root tty       7, 130  5月  1 20:54 vcsa2
crw-rw----   1 root tty       7, 131  5月  1 20:54 vcsa3
crw-rw----   1 root tty       7, 132  5月  1 20:54 vcsa4
crw-rw----   1 root tty       7, 133  5月  1 20:54 vcsa5
crw-rw----   1 root tty       7, 134  5月  1 20:54 vcsa6
crw-rw----   1 root tty       7, 136  5月  1 22:13 vcsa8
drwxr-xr-x   2 root root          60  5月  1 20:54 vfio/
crw-------   1 root root     10,  63  5月  1 20:54 vga_arbiter
crw-------   1 root root     10, 137  5月  1 20:54 vhci
crw-------   1 root root     10, 238  5月  1 20:54 vhost-net
crw-rw-rw-   1 root root      1,   5  5月  1 20:54 zero
`

I don't know how to integrated webcam device. Is it ok following your command in runDockerfile.sh?

thanks a lot!

**Comment by lbeaucourt** [comment]
Hi @lily0101 

By integrated I mean a webcam which is built-in into the laptop. I found this thread in askubuntu, maybe can you try some solutions to activate your device?

https://askubuntu.com/questions/461657/integrated-webcam-not-detected-after-update-to-14-04

If you found the name of your device in dev/, just modify in the runDocker.sh:

docker run [...] --device=/dev/video0 [...]  ==> replace video0 by your webcam device name

By the way, you can try to run this project on video file using the -i option in exec.sh (see README).

**Comment by lily0101** [comment]
@lbeaucourt  Hi, thanks a lot!
I will try that again! thanks again!

**Comment by sushant1727** [comment]
Is it possible to run this code in windows 10 with TFOD API?

**Comment by lbeaucourt** [comment]
Hi @sushant1727 !

I know you can use Docker with windows 10 Pro (not family!) as for linux (which is not the case for other windows versions). Now, I don't know how to send your webcam device stream from windows to docker.

Tensorflow Object-detection API is what I use in this project (but running locally). You can also run it on the google cloud: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_cloud.md

Bye

**Comment by sushant1727** [comment]
Thanks for the suggestion. I will look into it.
