### ISSUE TITLE
Can't find correct object_detection folder

### ISSUE THREAD

**Issue by mhvanzui** [lbeaucourt/Object-detection#5]
I'm having issues getting the "bash runDocker.sh" command to work properly. It keeps giving the error "bash: exec.sh: No such file or directory". When I run the command "bash exec.sh", it gives this error:

  File "/home/username/Object-detection/utils/objDet_utils.py", line 5, in <module>
    from object_detection.utils import label_map_util
ImportError: No module named 'object_detection'

I'm guessing this is because it can't find the tensorflow folder with the object_detection folder it needs. I followed the installation instructions and I hopefully have "told" python where the correct object_detection folder is. Any ideas?

**Comment by mhvanzui** [comment]
Alright I managed to find the object-detection folder it's talking about, but it is still unable to locate that folder properly

**Comment by lbeaucourt** [comment]
Hello @mhvanzui !

Sorry to answer so late. I had ton of things to do and not so much time to check this sandbox project last months ...

I hope you already find a solution to your problem. Nevertheless, the current version of this project work fine for me (running into the docker container from the provided dockerfile).

If you were trying to install tf-objectdetection outside of docker, I recommend you to take a look at the project github page (lot of usefull informations): https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md

Bye.
