### ISSUE TITLE
file missing

### ISSUE THREAD

**Issue by SouravGowda** [lbeaucourt/Object-detection#8]
from object_detection.utils import label_map_util
from object_detection.utils import visualization_utils as vis_util

i couldn't find the imported files

**Comment by lbeaucourt** [comment]
Hello @SouravGowda ,

First, sorry to answer so late, I have not so much time these days to work on this project ...

Did you tried to use tf-objectdetection with the provided dockerfile? If not, you could take a look here: https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md 

Let me know if it works!

Bye
