### ISSUE TITLE
How to modify the code to only get results for Person

### ISSUE THREAD

**Issue by isaactps** [lbeaucourt/Object-detection#9]
Hi Léo,

Currently, I am experimenting with using your Tensorflow object-detection API implementation to perform only **Person Detection** instead of detecting all 90 objects that are included in the MS COCO dataset.  A such, I will like to seek your advice on the approach to modify your implementation so that only the person/persons that are detected in either a video stream or a camera stream will be processed by downstream modules such as being highlighted in the output video etc.

Thank you very much for your advice in this experiment of mine.

Warmest Regards
Isaac Tan

**Comment by lbeaucourt** [comment]
Hi @isaactps ,

First, sorry to answer so late. I have tons of things to do last months ...

Maybe it's too late, but a quick way to ask tensorflow only look for persons is to modify the label file:

model/mscoco_label_map.pbtxt

where you find a list of items:

item {
  name: "/m/01g317"
  id: 1
  display_name: "person"
}
item {
  name: "/m/0199g"
  id: 2
  display_name: "bicycle"
}


Keep only the first one (person) label will be displayed in the output video stream!

This a first (and quick) way to achieve it. If you have some performance requirements, looking for another model trained to recognize only person (or train it by yourself!) will be the next step.

Hope this help you!

Bye

**Comment by lbeaucourt** [comment]
Hi Isaac,

Well, it's not as simple as I thought. As the model is looking for 90 different object classes, we cannot ask for only one item by modifying the label map file. I found a way to achieve this purpose (which I don't expect to be the optimal way to go, but it works): add this line in utils/objDet_utils.py at line 41 before visualization

> scores = scores * [classes[0] == 1]

Nevertheless, I suggest you to think about re-training your own model (using transfert-learning of course) to recognize only person.

Bye!

**Comment by isaactps** [comment]
Hi Leo,

Your suggestion works very well.  Thank you again for your great advice to this request of mine.

Warmest Regards
Isaac
